import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_excel("SuperStoreOrders.xlsx")
print("Rows")
print(df.head())
print("\nColumn names:")
print(df.columns)
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df['order_date'] = pd.to_datetime(df['order_date'],errors='coerce')
df.dropna(subset=['order_date'],inplace=True)
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
print("\nData after  cleaning")
print(df.info())
total_sales=df['sales'].sum()
print("total sales:",total_sales)
monthly_sales=df.groupby('month')['sales'].sum()
plt.figure()
monthly_sales.plot(kind='line',marker='o')
plt.title("monthly sales trend")
plt.xlabel("month")
plt.ylabel("sales")
plt.show()
top_products=df.groupby('product_name')['sales'].sum().sort_values(ascending=False).head(10)
plt.figure()
top_products.plot(kind='bar')
plt.title("TOP 10  products")
plt.xticks(rotation=45)
plt.show()
region_sales=df.groupby('region')['sales'].sum()
plt.figure()
region_sales.plot(kind='bar')
plt.title("sales by region")
plt.xlabel("region")
plt.ylabel("Sales")
plt.show()
category_sales=df.groupby('category')['sales'].sum()
plt.figure()
category_sales.plot(kind='pie',autopct='%1.1f%%')
plt.title("sales by category")
plt.ylabel("")
plt.show()
print("\nINSIGHTS:")
print("1.Sales are hihest during the month of December(seasonal trend)")
print("2.Technology category has the hightest sales")
print("3.West  region performs better than others")
print("4.Some months show less sales-imporvement needed")
df.to_excel("cleaned_sales_data.xlsx",index=False)
print("\nProject completed sccessfully")
